apiVersion: apps/v1
kind: Deployment
metadata:
  name: rms-deployment
  namespace: default
spec:
  replicas: 2  # Adjust as needed
  selector:
    matchLabels:
      app: rms
  template:
    metadata:
      labels:
        app: rms
    spec:
      containers:
      - name: rms
        # Use the ECR image. Replace <aws_account_id>, <region>, and <image_name> accordingly
        image: ${IMAGE_URL}:latest
        ports:
        - containerPort: 8000  # Django app running on port 8000
        env:
        - name: DATABASE_NAME
          value: "${DB_NAME}"  # Variable for database name
        - name: DATABASE_USER
          value: "${DB_USERNAME}"
        - name: DATABASE_HOST
          value: "${DB_HOST}"  # Variable for database name
        - name: DATABASE_PASSWORD
          value: "${DB_PASSWORD}"
        - name: DATABASE_PORT
          value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: rms-service
  namespace: default
spec:
  selector:
    app: rms
  ports:
    - protocol: TCP
      port: 80  # Exposed service port
      targetPort: 8000  # Django app's container port
  type: LoadBalancer